version: "3.8"

services:
  app:
    build: .
    depends_on:
      - postgres
    image: romanovosad/example-postgres-app
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:$SPRING_DOCKER_PORT
      - ${DEBUG_PORT}:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:postgresql://postgres:$POSTGRES_DOCKER_PORT/$POSTGRES_DB",
      "spring.datasource.username" : "$POSTGRES_USER",
      "spring.datasource.password" : "$POSTGRES_PASSWORD",
      "spring.jpa.show-sql" : "true"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"


  postgres:
    image: postgres
    container_name: postgres
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5






